{{- if .Values.jwtRefresh.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jwt-refresh.name" . }}
  namespace: {{ include "main-namespace" . }}
  labels:
    {{- include "jwt-refresh.labels" . | nindent 4 }}
  {{- with (include "jwt-refresh.service-account-annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
