{{- if and .Values.nodeDoctor.enabled .Values.nodeDoctor.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "node-doctor.name" . }}
  namespace: {{ include "main-namespace" . }}
  labels:
    {{- include "node-doctor.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch" ]
{{- end }}
