{{- if and .Values.nodeDoctor.enabled .Values.nodeDoctor.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "node-doctor.name" . }}
  labels:
    {{- include "node-doctor.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "node-doctor.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "node-doctor.name" . }}
    namespace: {{ include "main-namespace" . }}
{{- end }}
