{{- if and .Values.nodeDoctor.enabled .Values.nodeDoctor.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-doctor.name" . }}
  namespace: {{ include "main-namespace" . }}
  labels:
    {{- include "node-doctor.labels" . | nindent 4 }}
  {{- with (include "node-doctor.service-account-annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
