{{- if and .Values.worker.enabled .Values.runs.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "runs.name" . }}
  namespace: {{ include "runs-namespace" . }}
  labels:
    {{- include "runs.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "runs.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "runs.name" . }}
    namespace: {{ include "runs-namespace" . }}
{{- end }}
