{{- if and .Values.worker.enabled .Values.runs.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "runs.name" . }}
  namespace: {{ include "runs-namespace" . }}
  labels:
    {{- include "runs.labels" . | nindent 4 }}
  {{- with (include "runs.service-account-annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
