apiVersion: v1
kind: Secret
metadata:
  name: {{ include "compute-plane.service-api-key.name" . }}
  namespace: {{ include "main-namespace" . }}
  labels:
    {{- include "compute-plane.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  serviceApiKey: {{ .Values.apiKey }}
