apiVersion: v1
kind: Secret
metadata:
  name: {{ include "compute-plane.service-jwt.name" . }}
  namespace: {{ include "main-namespace" . }}
  labels:
    "mosaicml.com/secret-type": COMPUTE_PLANE_SERVICE_JWT
    {{- include "compute-plane.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  accessToken: ""
