{{- if and .Values.worker.enabled .Values.worker.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "worker.name" . }}
  namespace: {{ include "main-namespace" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
  {{- with (include "worker.service-account-annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
